version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  dgraph:
    image: dgraph/dgraph:latest
    volumes:
      - ./data/dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=dgraph:7080 --zero=zero:5080 --lru_mb=2048
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
  app:
    build: .
    volumes:
      - .:/go/src/github.com/sergeyt/pandora
    ports:
      - 3000:3000
  caddy:
    image: abiosoft/caddy:latest
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./data/caddycerts:/etc/caddycerts
    ports:
      - 4200:4200
