version: "3.2"
services:
  dgraph:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: >
      bash -c "dgraph zero
      && dgraph server --memory_mb=2048 --bindall
      && dgraph-ratel --port=8888"
  caddy:
    image: abiosoft/caddy
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/Caddyfile
    ports:
      - 8000:8000
    command: caddy

volumes:
  dgraph:
